language: objective-c
osx_image: xcode7.2

before_install:
  - brew update
  - brew upgrade xctool

install:
  - bundle install

script: 
  - xctool -project reCreation.xcodeproj -scheme reCreation -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project reCreation.xcodeproj -scheme reCreation -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO